version 6.x
set fileformats=unix
syntax on

hi Comment      term=bold       ctermfg=Yellow      guifg=LightBlue
hi Constant     term=underline  ctermfg=Green       guifg=Green             gui=underline
hi Identifier   term=underline  ctermfg=LightCyan   guifg=DarkCyan
hi Statement    term=bold       ctermfg=Magenta     guifg=Brown             gui=bold
hi PreProc      term=underline  ctermfg=Magenta     guifg=Purple
hi Type         term=underline  ctermfg=DarkGreen   guifg=SeaGreen          gui=bold
hi Special      term=bold       ctermfg=LightBlue   guifg=SlateBlue         gui=underline

hi Comment      cterm=NONE
hi Constant     cterm=NONE
hi Identifier   cterm=NONE
hi Statement    cterm=NONE
hi PreProc      cterm=NONE
hi Type         cterm=NONE
hi Special      cterm=NONE

set backspace=2

set gfn=-b&h-lucidatypewriter-medium-r-normal-*-*-120-*-*-m-*-iso8859-1
set whichwrap=<,>,[,]
set autoindent
set incsearch
set background=dark
set formatoptions=tcq2
set mouse=a
set ruler
set shiftwidth=4
set showmatch
set textmode

set softtabstop=4
set expandtab
set ruler
set sw=4
set showmatch
set ai

hi Normal guibg=black
hi Normal guifg=gray80

set nobackup
set cmdheight=2

set nocompatible
