#!/bin/bash

set -e

# suppress CS50 compilation preferences
unset CC CFLAGS LDLIBS

echo "Adding external repos..."

# install apt-transport-https
sudo rm -f /etc/apt/sources.list.d/github_git-lfs.list
sudo apt-get update && sudo apt-get install -y apt-transport-https

# add external apt repos
# install cs50 ppa
if [ ! -f /etc/apt/sources.list.d/cs50-ppa-trusty.list ]; then
    sudo add-apt-repository -y ppa:cs50/ppa
    sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cs50-ppa-trusty.list" \
        -o Dir::Etc::sourceparts="-"
fi

# install git-core ppa
if [ ! -f /etc/apt/sources.list.d/git-core-ppa-trusty.list ]; then
    sudo add-apt-repository ppa:git-core/ppa
    sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/git-core-ppa-trusty.list" \
        -o Dir::Etc::sourceparts="-"
fi

# install git-lfs apt repo
# https://packagecloud.io/github/git-lfs/install#manual
if [ ! -f /etc/apt/sources.list.d/github_git-lfs.list ]; then
    curl -sSL https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -
    echo "deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main" | sudo tee /etc/apt/sources.list.d/github_git-lfs.list && \
        echo "deb-src https://packagecloud.io/github/git-lfs/ubuntu/ trusty main" | sudo tee -a /etc/apt/sources.list.d/github_git-lfs.list
    sudo chmod a+r /etc/apt/sources.list.d/github_git-lfs.list
    sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/github_git-lfs.list" \
        -o Dir::Etc::sourceparts="-"
fi

echo "Updating sources..."
# try to fix dpkg before updating
sudo dpkg --configure -a

# if requested, flush the apt-get Packages file cache
if [ "$1" == "-f" ]; then
    echo "CLEARING PACKAGE CACHE"
    sudo rm -rf /var/lib/apt/lists/*
fi

sudo apt-get update

echo "Reinstalling ide package..."
sudo -E apt-get -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" install --reinstall --yes --force-yes --assume-yes ide50

echo "Installing other packages..."

# node 7.6.0
export NVM_DIR="/home/ubuntu/.nvm"
. $NVM_DIR/nvm.sh
nvm install 7.6.0
nvm alias default 7.6.0

# composer
# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-14-04
if ! which composer &>/dev/null; then
    curl -sS https://getcomposer.org/installer | \
        sudo php -- --install-dir=/usr/local/bin --filename=composer
fi

# hub
# https://hub.github.com/
# http://stackoverflow.com/a/27869453
if ! which hub &>/dev/null; then
    mkdir /tmp/hub-linux-amd64 && \
        curl -s -L https://github.com/github/hub/releases/latest | \
        egrep -o '/github/hub/releases/download/.*/hub-linux-amd64-.*.tgz' | \
        wget --base=http://github.com/ -i - -O - | \
        tar xvz -C /tmp/hub-linux-amd64 --strip-components 1 && \
        sudo /tmp/hub-linux-amd64/install && \
        rm -rf /tmp/hub-linux-amd64
fi

# pyenv
export PYENV_ROOT="/opt/pyenv"
if ! which pyenv &>/dev/null; then
    sudo apt-get install -y \
        build-essential \
        curl \
        libbz2-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        llvm \
        wget \
        xz-utils \
        zlib1g-dev
    wget -P /tmp https://github.com/yyuu/pyenv/archive/master.zip
    unzip -q -d /tmp /tmp/master.zip
    rm -f /tmp/master.zip
    sudo mv /tmp/pyenv-master /opt/pyenv
fi
/opt/pyenv/bin/pyenv install --skip-existing 3.6.0
/opt/pyenv/bin/pyenv rehash
/opt/pyenv/bin/pyenv global 3.6.0

echo "Removing unneeded packages..."
/usr/bin/sudo apt-get autoremove -y

echo "Installing Python packages..."

# clean up pip's build cache
/usr/bin/sudo rm -rf /tmp/pip_build_root/*

# use pip for python3.6
unset PYTHONPATH
export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# install python packages
PYTHON_PACKAGES="check50==2.0.1 \
    cs50==2.2.0 \
    Flask \
    Flask-SQLAlchemy \
    Flask-Session \
    help50==2.0.0 \
    render50==2.0.1 \
    SQLAlchemy \
    submit50==2.4.0 \
    virtualenv"
( /usr/bin/sudo pip3 install $PYTHON_PACKAGES )

echo "Update complete!"
echo -e "\nBE SURE TO CLOSE AND RE-OPEN ANY TERMINAL WINDOWS <3\n"
