#!/bin/bash

echo "Resetting permissions ..."

chmod -R g+w /home/ubuntu/workspace
chown -R ubuntu:ubuntu /home/ubuntu >/dev/null 2>&1
chown -R ubuntu:ubuntu /var/c9sdk/plugins/c9.ide.cs50* >/dev/null 2>&1
chown -R ubuntu:ubuntu /var/c9sdk/configs/ >/dev/null 2>&1

chmod 755 /usr/bin/version50

echo "Setting configuration files ..."
chmod 644 /etc/profile.d/ide50.sh

# remove dropbox functions
sed -i 's:source /home/ubuntu/.dropbox50::g' ~/.bashrc

groupadd -r courses > /dev/null 2>&1 || true
adduser --gecos "CS50,,,," --ingroup courses --disabled-login --system cs50 > /dev/null 2>&1 || true

chown -R cs50.courses /home/cs50
find /home/cs50 -type d -exec chmod 755 {} \;
find /home/cs50 -type f -exec chmod 644 {} \;
chmod 711 /home/cs50/pset1/{mario,greedy,water} /home/cs50/hacker1/{credit,mario,water} /home/cs50/hacker2/initials /home/cs50/pset2/{initials,caesar,vigenere,devigenere} /home/cs50/pset3/find /home/cs50/hacker3/find /home/cs50/pset4/{peek,resize} /home/cs50/hacker4/{peek,resize} /home/cs50/pset5/speller /home/cs50/pset6/server
chmod 755 /home/cs50/pset5/challenge

# prep instance's index page
if [ -f /var/www/html/index.html ]; then
    rm -f /var/www/html/index.html
fi

# remove apache test file from workspace
if grep -qs '^Success$' /var/www/html/file; then
    rm -f /var/www/html/file
fi

# add ide50 source file to apache's envvars
if ! grep -qs 'ide50.sh' /etc/apache2/envvars; then
    sed -i 's-cloud9.sh-cloud9.sh\n. /etc/profile.d/ide50.sh-' /etc/apache2/envvars
fi

rm -rf /home/ubuntu/cs50
# remove old source file if it exists
if [ -f /etc/profile.d/app.sh ]; then
    rm -f /etc/profile.d/app.sh
fi

# create a password50 file, if it doesn't exist
sudo -Eu ubuntu /usr/bin/password50 >/dev/null 2>&1

####################
# the remaining requires a recent update50 and some env variables must exist
if [ -z "$C9_USER" ]; then
    echo
    echo "Please run update50 again to complete the installation!"
    exit 0
fi

# set up MySQL
echo "Setting up MySQL ..."
/usr/bin/mysql50 install >/dev/null 2>&1

if [ ${IDE_OFFLINE+x} ]; then
    # offline only: update c9sdk and plugins
    echo "Updating Cloud9 SDK ..."
    pushd /var/c9sdk >/dev/null 2>&1
    sudo -Eu ubuntu scripts/install-sdk.sh stop >/dev/null 2>&1
    popd >/dev/null 2>&1
    echo
    echo "All done! <3"
    echo "Please reload your workspace to get the latest updates!"
else
    # plugin updates aren't necessary for online IDEs
    rm -rf /var/c9sdk/plugins/c9.ide.cs50* >/dev/null 2>&1
    rmdir -p /var/c9sdk/plugins/ >/dev/null 2>&1

    rm -rf /var/c9sdk/configs/client-workspace-cs50.js >/dev/null 2>&1
    rmdir -p /var/c9sdk/configs/ >/dev/null 2>&1

    echo
    echo "All done! <3"
fi

exit 0
