#!/bin/bash

echo "Resetting permissions.."

chmod -R g+w /home/ubuntu/workspace 
chown -R ubuntu:ubuntu /home/ubuntu >/dev/null 2>&1

pwd
    
chmod 755 /usr/bin/version50 
   
echo "Setting configuration files.."
mv /home/ubuntu/cs50/app.sh /etc/profile.d
mv /home/ubuntu/cs50/cs50.conf /etc/apache2/conf-available 
ln -fs /etc/apache2/conf-available/cs50.conf /etc/apache2/conf-enabled/cs50.conf 

mv /home/ubuntu/cs50/dropbox50 /home/ubuntu/.dropbox50

echo "source /home/ubuntu/.dropbox50" >> /home/ubuntu/.bashrc

groupadd -r courses > /dev/null 2>&1 || true
adduser --gecos "CS50,,,," --ingroup courses --disabled-login --system cs50 > /dev/null 2>&1 || true

chown -R cs50.courses /home/cs50
find /home/cs50 -type d -exec chmod 755 {} \;
find /home/cs50 -type f -exec chmod 644 {} \;
chmod 711 /home/cs50/pset1/{mario,greedy} /home/cs50/hacker1/{credit,mario} /home/cs50/hacker2/initials /home/cs50/pset2/{initials,caesar,vigenere,devigenere} /home/cs50/pset3/find /home/cs50/hacker3/find /home/cs50/pset4/{peek,resize} /home/cs50/hacker4/{peek,resize} /home/cs50/pset5/speller /home/cs50/pset6/server
chmod 755 /home/cs50/pset5/challenge

mv /home/ubuntu/cs50/index.php /var/www/html/index.php
rm /var/www/html/index.html 2> /dev/null
chmod 644 /var/www/html/index.php

rm -rf /home/ubuntu/cs50

phpmyadmin-ctl install

exit 0
