#!/bin/bash

mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts

export HOME=/root
export LC_ALL=C

# generate /etc/resolve.conf
resolvconf -u

debconf-set-selections <<< 'iptables-persistent     iptables-persistent/autosave_v4 boolean false'
debconf-set-selections <<< 'iptables-persistent     iptables-persistent/autosave_v6 boolean false'

debconf-set-selections <<< 'phpmyadmin phpmyadmin/dbconfig-install boolean true'
debconf-set-selections <<< 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2'
debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/admin-user string root'
debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/admin-pass password crimson'
#debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/admin-user string jharvard'
debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/app-pass password'


chmod 1777 /tmp
apt-get update
apt-get upgrade
apt-get -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" install --yes --force-yes --assume-yes appliance50
apt-get upgrade

# fix installer crash
rm -f /usr/lib/ubiquity/apt-setup/generators/40cdrom

# chmod ping appropriately (it's missing the setuid bit)
chmod u+s /bin/ping{,6}

rm /var/lib/dbus/machine-id
rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl
ls /boot/vmlinuz-**-generic > list.txt
sum=$(cat list.txt | grep '[^ ]' | wc -l)

if [ $sum -gt 1 ]; then
    dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | xargs apt-get -y purge
fi

# needed?
service mysql stop
service apache2 stop

rm list.txt
apt-get dist-upgrade
apt-get clean
apt-get autoremove
rm -rf /tmp/*

# https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/811441 (fixes "waiting for network configuration")
rm -rf /var/run/dbus

umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
