#!/bin/bash
cd build

# clear dbus directory, which causes "Waiting for network configuration" issues
rm -rf chroot/var/run/dbus/

# remove previously generated image, if any
rm -rf image
rm -f appliance50.iso

# copy boot things
umount -lf chroot/dev 2> /dev/null
mkdir -p image/{casper,isolinux,install}
cp chroot/boot/vmlinuz*-generic image/casper/vmlinuz
cp chroot/boot/initrd*-generic image/casper/initrd.lz

# modify initrd.gz to fix Live CD username issue
cd image/casper
mkdir tempdir
cd tempdir
mv ../initrd.lz initrd.gz
gunzip -dc initrd.gz | cpio -imd --no-absolute-filenames
cp -f ../../../../casper.conf etc/
# for some reason, initrd.lz, not .gz
find . | cpio -o -H newc | gzip -9 > ../initrd.lz
cd ..
rm -rf tempdir
cd ../..


rm -rf chroot/{vmware-tools,parallels,vbox}
cp -r ../tools/vmware-tools chroot/vmware-tools
cp -r ../tools/vbox chroot/vbox
cp -r ../tools/parallels chroot/parallels

cp /boot/memtest86+.bin image/install/memtest

cp -R ../image  .

chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee image/casper/filesystem.manifest
cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
REMOVE='ubiquity ubiquity-frontend-gtk ubiquity-frontend-kde casper lupin-casper live-initramfs user-setup discover1 xresprobe os-prober libdebian-installer4'
for i in $REMOVE
do
        sed -i "/${i}/d" image/casper/filesystem.manifest-desktop
done

mksquashfs chroot image/casper/filesystem.squashfs

printf $(du -sx --block-size=1 chroot | cut -f1) > image/casper/filesystem.size

echo 'cd image/ && find . -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > md5sum.txt' | sh

IMAGE_NAME="CS50 Appliance 2014"

cd image
mkisofs -D -r -V "$IMAGE_NAME" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../appliance50.iso .
chmod 644 ../appliance50.iso
